### Indexing

In [1]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([6, 7, 9, 6, 1, 3, 8, 6, 3, 7])

In [2]:
a[0]

6

In [3]:
a[-1]

7

In [4]:
a[2] = 11
a

array([ 6,  7, 11,  6,  1,  3,  8,  6,  3,  7])

In [5]:
m = np.random.randint(10, size = (3,5))
m

array([[4, 8, 5, 0, 6],
       [6, 7, 9, 7, 4],
       [5, 5, 9, 9, 7]])

In [6]:
m[1,2]

9

### Slicing

In [7]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [8]:
a[0:3]

array([20, 21, 22])

In [9]:
a[1::2]

array([21, 23, 25, 27, 29])

In [10]:
m = np.random.randint(10, size = (5,5))
m

array([[7, 9, 6, 2, 2],
       [3, 4, 7, 9, 8],
       [1, 7, 3, 3, 4],
       [8, 7, 6, 5, 8],
       [6, 1, 3, 4, 5]])

In [11]:
m[:,0] # satırlarda kısıtlama yok, sütunlardan sadece 0. indexi al 

array([7, 3, 1, 8, 6])

In [12]:
m[3,:] # 3. indexli satır, tüm sütunlar  = m[3]

array([8, 7, 6, 5, 8])

In [13]:
m[0:2,0:3] # 2'ye kadar satırlar, 3'e kadar sütunlar

array([[7, 9, 6],
       [3, 4, 7]])

**!!** Herhangi bir arrayin slicing ile alt kümesini bir değişkene atayıp o alt kümede bir değişiklik yaptığımızda orijinal arrayde de bir değişiklik olmaktadır. (_shallow copy_) Böyle durumlarda alt kümeleri **bağımsızlaştırmalıyız!**

In [15]:
x = np.random.randint(10, size = (5,5))
x

array([[0, 3, 6, 4, 1],
       [6, 8, 3, 4, 2],
       [8, 6, 3, 2, 9],
       [3, 4, 0, 7, 9],
       [8, 9, 3, 9, 7]])

In [16]:
alt = x[0:3,0:2]
alt

array([[0, 3],
       [6, 8],
       [8, 6]])

In [17]:
alt[0,0] = 9
alt

array([[9, 3],
       [6, 8],
       [8, 6]])

In [18]:
x # !! x de değişti !!

array([[9, 3, 6, 4, 1],
       [6, 8, 3, 4, 2],
       [8, 6, 3, 2, 9],
       [3, 4, 0, 7, 9],
       [8, 9, 3, 9, 7]])

Bağımsızlaştırma işlemi için **copy()** kullanılır.

In [20]:
alt2 = x[0:3,0:2].copy()
alt2

array([[9, 3],
       [6, 8],
       [8, 6]])

In [21]:
alt2[0,0] = 100
alt2

array([[100,   3],
       [  6,   8],
       [  8,   6]])

In [22]:
x # !! x değişmedi !!

array([[9, 3, 6, 4, 1],
       [6, 8, 3, 4, 2],
       [8, 6, 3, 2, 9],
       [3, 4, 0, 7, 9],
       [8, 9, 3, 9, 7]])

### Fancy Indexing

In [23]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [24]:
[v[1],v[3],v[5]]

[3, 9, 15]

Yukarıdaki örnekte istenen her eleman için tek tek arraye eriştik. _Fancy indexing_ ile bunu değiştirebiliriz.

In [25]:
indexes = [1,3,5]
v[indexes]

array([ 3,  9, 15])

In [26]:
y = np.arange(9).reshape((3,3))
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
line = [0,1]
column = [1,2]
y[line,column] # 0. satır 1. sütun ve 1. satır 2. sütun (iki listin aynı indexteki elemanları)

array([1, 5])

In [30]:
y[0,[1,2]] # basit index ve fancy index

array([1, 2])

In [31]:
y[0:, [1,2]] # slicing ve fancy index

array([[1, 2],
       [4, 5],
       [7, 8]])

### Koşullu Eleman İşlemleri

In [33]:
v = np.array([1,2,3,4,5])
v < 3

array([ True,  True, False, False, False])

In [34]:
v[v < 3]

array([1, 2])

### Matematiksel İşlemler

In [35]:
v = np.array([1,2,3,4,5])
v * 5

array([ 5, 10, 15, 20, 25])

Yaptığımız bu işlemler **ufunc** dediğimiz metodları çağırmaktadır.
**ex:** v-1 ==> np.subtract(v,1)

In [37]:
np.absolute(np.array([-3]))

array([3])

In [38]:
np.sin(360) # trigonometrik işlemler gerçekleştirilebilir.

0.9589157234143065

In [39]:
np.log(np.array([1,2,3])) # logaritmik işlemler gerçekleştirilebilir.

array([0.        , 0.69314718, 1.09861229])

In [40]:
np.log2(np.array([1,2,3])) # almak istediğimiz log tabanları sağdaki gibi kullanılır.

array([0.       , 1.       , 1.5849625])

### 2 Bilinmeyenli Denklem Çözümü

**ex:** 5 * x0 + x1 = 12 <br>
x0 + 3 * x1= 10

In [41]:
a = np.array([[5,1], [1,3]]) # katsayılar listesi
b = np.array([12,10]) # sonuçlar listesi
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])