Numpy arraylerinin Pythondaki listlerden farkı -> 1) fixed type olması böylelikle her eleman için tip bilgisi tutmuyor => verimli saklama
                                                  2) vektörel işlemler sayesinde kolaylık sağlıyor olması 

### Vektörel işlem nedir?

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

## Numpy Arrayleri

In [4]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

In [5]:
np.array([3.14,4,2,13], dtype = "int")

array([ 3,  4,  2, 13])

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [8]:
np.full((3,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [9]:
np.arange(0,31,3) # 3 ile 31 arasında 3'erli artan değerler

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [10]:
np.linspace(0,1,10) # 1 ile 10 arasında 10 tane değer

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [11]:
np.random.normal(10,4,(3,4)) # ortalaması 10, standart sapması 4 olan normal dağılmış matrix

array([[ 9.4902621 , 13.39263796, 16.06344512, 12.81963567],
       [11.35773964,  8.0718639 ,  9.92092917, 14.2923633 ],
       [11.34949714,  4.87474307,  5.60645826,  8.34555514]])

In [13]:
np.random.randint(0,10,(3,3)) # 0 ile 10 arasında random integer matrixi oluştur

array([[7, 1, 5],
       [3, 5, 0],
       [5, 1, 8]])

### Özellikler

**ndim** -> boyut  sayısı
**shape** -> boyut bilgisi
**size** -> eleman sayısı
**dtye** -> veri tipi

In [15]:
a = np.random.randint(10, size = 10)
a.ndim

1

In [16]:
a.shape # tek boyutunun bilgisi verilmiş, 10 tane eleman var diyor

(10,)

In [17]:
a.size

10

In [18]:
a.dtype

dtype('int32')

### Reshaping

In [19]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.full((3,5),3).reshape(15)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

Arraylerin boyutlarını değiştirip düzenlemek için kullanılır.

### Concatenation

In [21]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [24]:
a = np.array([[1,2,3],[4,5,6]])
np.concatenate([a,a,a]) # iki boyutlu arrayleri satır bazında birleştirme

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [25]:
np.concatenate([a,a], axis = 1) # iki boyurlu arrayleri sütun bazında birleştirme

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Arrayleri birleştirmek için kullanılır.

### Splitting

In [26]:
x = np.array([1,2,3,99,99,3,2,1])
np.split(x, [3,5]) # 3'e kadar ve 5'e kadar ayır

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [28]:
a,b,c = np.split(x, [3,5]) # ayırdıklarımızı atamak için
c

array([3, 2, 1])

In [30]:
m = np.arange(16).reshape(4,4)
np.vsplit(m,[2]) # 2. satıra kadarını ayır

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [31]:
np.hsplit(m, [2]) # 2. sütuna kadarını ayır

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
Yapısını bildiğimiz arrayleri parçalamak için kullanılır.

### Sorting

In [32]:
v = np.array([2,1,4,3,5])
np.sort(v)

array([1, 2, 3, 4, 5])

In [33]:
v # hala aynı

array([2, 1, 4, 3, 5])

In [34]:
v.sort()
v # şimdi yapı değişti

array([1, 2, 3, 4, 5])

In [35]:
m = np.random.normal(20,5,(3,3)) # 2 boyutta sıralama
np.sort(m, axis = 1) # her bir satırı kendi içinde küçükten büyüğe sıralar

array([[15.52135368, 24.5052627 , 30.02542145],
       [14.26906981, 19.98306808, 21.80386118],
       [15.88438574, 17.93483971, 18.07357346]])

In [36]:
np.sort(m, axis = 0) # her bir sütunu kendi içinde sıralar

array([[15.88438574, 17.93483971, 14.26906981],
       [19.98306808, 21.80386118, 15.52135368],
       [24.5052627 , 30.02542145, 18.07357346]])

### Extra

In [38]:
5*np.array([1,2,3])

array([ 5, 10, 15])